steps:
- name: 'gcr.io/cloud-builders/docker' 
  args: ['build', '-t', 'gcr.io/beaming-ring-289904/forest-fire:$SHORTSHA', '.']
- name: 'gcr.io/cloud-builders/docker' 
  args: ['push','gcr.io/beaming-ring-289904/forest-fire:$SHORTSHA']
