steps:
- name: 'gcr.io/cloud-builders/docker' 
  args: ['build', '-t', 'gcr.io/beaming-ring-289904/github.com/mkaka182/forest-fire:$SHORT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker' 
  args: ['push','gcr.io/beaming-ring-289904/github.com/mkaka182/forest-fire:$SHORT_SHA']
- name: 'gcr.io/cloud-builders/gcloud' 
  args: ['beta','run', 'deploy', 'beaming-ring-289904', '--region=europe-west1', '--platform=managed','--image=gcr.io/beaming-ring-289904/github.com/mkaka182/forest-fire:$SHORT_SHA']
